### ISSUE TITLE
进度监听回调有问题

### ISSUE THREAD

**Issue by moujunqiang** [zsgfrtttt/HttpUtil#1]
在使用多线程下载的时候，返现进度监听那块有问题，每次文件下载完成了进度还一直在跑，直到值为199

**Comment by zsgfrtttt** [comment]
有对应的url么，我看下




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zsgfrtttt/HttpUtil"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月18日(星期二) 下午5:00
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[zsgfrtttt/HttpUtil] 进度监听回调有问题 (Issue #1)





 
在使用多线程下载的时候，返现进度监听那块有问题，每次文件下载完成了进度还一直在跑，直到值为199
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by moujunqiang** [comment]
用的是demo中提供的url，







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zsgfrtttt/HttpUtil"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月18日(星期二) 下午5:10
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zsgfrtttt/HttpUtil] 进度监听回调有问题 (Issue #1)





 有对应的url么，我看下 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "zsgfrtttt/HttpUtil"                                                                                    ***@***.***&amp;gt;; 
 发送时间:&amp;nbsp;2022年1月18日(星期二) 下午5:00 
 ***@***.***&amp;gt;; 
 ***@***.***&amp;gt;; 
 主题:&amp;nbsp;[zsgfrtttt/HttpUtil] 进度监听回调有问题 (Issue #1) 
 
 
 
 
 
   
 在使用多线程下载的时候，返现进度监听那块有问题，每次文件下载完成了进度还一直在跑，直到值为199 
   
 — 
 Reply to this email directly, view it on GitHub, or unsubscribe. 
 Triage notifications on the go with GitHub Mobile for iOS or Android.  
 You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&amp;gt; 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by moujunqiang** [comment]
直接用的demo中提供的utl,
![image](https://user-images.githubusercontent.com/22389682/149911041-620076f0-8f12-4c6f-94f8-808d88029efa.png)
![image](https://user-images.githubusercontent.com/22389682/149911108-86597a65-c855-4db3-95e8-5e44674eb679.png)

**Comment by moujunqiang** [comment]
应该是checkDownloadCompleted这个方法的原因，我把调用这个方法的地方注释掉，就正常了，但是下载进度慢了很多，具体原因还没研究明白
![image](https://user-images.githubusercontent.com/22389682/149916273-cd5610b9-f9d0-485e-a5b1-326391361683.png)

**Comment by zsgfrtttt** [comment]
> 应该是checkDownloadCompleted这个方法的原因，我把调用这个方法的地方注释掉，就正常了，但是下载进度慢了很多，具体原因还没研究明白 ![image](https://user-images.githubusercontent.com/22389682/149916273-cd5610b9-f9d0-485e-a5b1-326391361683.png)

已修复 implementation 'com.github.zsgfrtttt.HttpUtil:download-core:1.1.1@aar'
    	     implementation ("com.squareup.okhttp3:okhttp:4.2.1")
